In [1]:
import numpy as np

In [3]:
# 임의의값 생성
data = np.random.randn(2, 3)

In [4]:
data

array([[-0.94069461, -2.37199741,  0.41749139],
       [-0.09791343, -0.3130233 , -0.45917075]])

In [5]:
data * 10

array([[ -9.40694609, -23.71997414,   4.17491386],
       [ -0.9791343 ,  -3.13023303,  -4.59170746]])

In [6]:
data + data

array([[-1.88138922, -4.74399483,  0.83498277],
       [-0.19582686, -0.62604661, -0.91834149]])

In [7]:
data1 = [6, 7.5, 8, 0, 1]

In [8]:
arr1 = np.array(data1)

In [9]:
arr1

array([6. , 7.5, 8. , 0. , 1. ])

In [10]:
data2 = [[1, 2, 3, 4], [5, 6, 7, 8]]

In [11]:
arr2 = np.array(data2)

In [12]:
arr2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [13]:
arr2.ndim

2

In [14]:
arr2.shape

(2, 4)

In [15]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [16]:
np.zeros((3, 6))

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [17]:
np.zeros((2, 3, 2))

array([[[0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.]]])

In [19]:
np.empty(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])