In [9]:
import pandas as pd
import numpy as np

In [2]:
obj = pd.Series([4, 7, -5, -3])

In [3]:
obj2 = pd.Series([4, 7, -5, -3], index = ['d', 'b', 'a', 'c'])

In [4]:
obj2['a']

-5

In [6]:
obj2[obj2 > 0]

d    4
b    7
dtype: int64

In [7]:
obj.isnull()

0    False
1    False
2    False
3    False
dtype: bool

In [8]:
obj2 * 2

d     8
b    14
a   -10
c    -6
dtype: int64

In [10]:
np.exp(obj)

0      54.598150
1    1096.633158
2       0.006738
3       0.049787
dtype: float64

In [14]:
sdata = {'Ohio' : 35000, 'Texas' : 71000, 'Oregon' : 16000, 'Utah' : 5000}

In [15]:
obj3 = pd.Series(sdata)

In [13]:
states = ['California', 'Ohio', 'Oregon', 'Texas']

In [16]:
obj4 = pd.Series(sdata, index=states)

In [17]:
obj.index

RangeIndex(start=0, stop=4, step=1)

In [18]:
obj2.index

Index(['d', 'b', 'a', 'c'], dtype='object')

In [19]:
obj4

California        NaN
Ohio          35000.0
Oregon        16000.0
Texas         71000.0
dtype: float64

In [20]:
pd.isnull(obj4)

California     True
Ohio          False
Oregon        False
Texas         False
dtype: bool

In [21]:
pd.notnull(obj4)

California    False
Ohio           True
Oregon         True
Texas          True
dtype: bool

In [22]:
obj4.isnull()

California     True
Ohio          False
Oregon        False
Texas         False
dtype: bool

In [23]:
obj3

Ohio      35000
Texas     71000
Oregon    16000
Utah       5000
dtype: int64

In [24]:
obj4

California        NaN
Ohio          35000.0
Oregon        16000.0
Texas         71000.0
dtype: float64

In [25]:
obj3 + obj4

California         NaN
Ohio           70000.0
Oregon         32000.0
Texas         142000.0
Utah               NaN
dtype: float64

In [26]:
obj4.name = 'population'

In [27]:
obj4.index.name = 'state'

In [28]:
obj4

state
California        NaN
Ohio          35000.0
Oregon        16000.0
Texas         71000.0
Name: population, dtype: float64

In [29]:
obj.index = ['Bob', 'Steve', 'Jeff', 'Ryan']

In [30]:
obj

Bob      4
Steve    7
Jeff    -5
Ryan    -3
dtype: int64

In [31]:
data = {'state' : ['Ohio', 'Ohio', 'Ohio', 'Nevada', 'Nevada', 'Nevada'],
        'year' : [2000, 2001, 2002, 2001, 2002, 2003],
        'pop' : [1.5, 1.7, 3.6, 2.4, 2.9, 3.2]}
frame = pd.DataFrame(data)

In [32]:
frame

state  year  pop
0    Ohio  2000  1.5
1    Ohio  2001  1.7
2    Ohio  2002  3.6
3  Nevada  2001  2.4
4  Nevada  2002  2.9
5  Nevada  2003  3.2

In [33]:
frame.head()

state  year  pop
0    Ohio  2000  1.5
1    Ohio  2001  1.7
2    Ohio  2002  3.6
3  Nevada  2001  2.4
4  Nevada  2002  2.9

In [34]:
pd.DataFrame(data, columns=['year', 'state', 'pop'])

year   state  pop
0  2000    Ohio  1.5
1  2001    Ohio  1.7
2  2002    Ohio  3.6
3  2001  Nevada  2.4
4  2002  Nevada  2.9
5  2003  Nevada  3.2

In [35]:
frame2 = pd.DataFrame(data, columns=['year', 'state', 'pop', 'debt'],
                     index=['one', 'two', 'three', 'four', 'five', 'six'])

In [36]:
frame2

year   state  pop debt
one    2000    Ohio  1.5  NaN
two    2001    Ohio  1.7  NaN
three  2002    Ohio  3.6  NaN
four   2001  Nevada  2.4  NaN
five   2002  Nevada  2.9  NaN
six    2003  Nevada  3.2  NaN

In [37]:
frame2.columns

Index(['year', 'state', 'pop', 'debt'], dtype='object')

In [38]:
frame2['state']

one        Ohio
two        Ohio
three      Ohio
four     Nevada
five     Nevada
six      Nevada
Name: state, dtype: object

In [39]:
frame2.year

one      2000
two      2001
three    2002
four     2001
five     2002
six      2003
Name: year, dtype: int64

In [41]:
frame2.loc['three']

year     2002
state    Ohio
pop       3.6
debt      NaN
Name: three, dtype: object

In [42]:
frame2['debt'] = 16.5

In [43]:
frame2

year   state  pop  debt
one    2000    Ohio  1.5  16.5
two    2001    Ohio  1.7  16.5
three  2002    Ohio  3.6  16.5
four   2001  Nevada  2.4  16.5
five   2002  Nevada  2.9  16.5
six    2003  Nevada  3.2  16.5

In [47]:
frame2['debt'] = np.arange(6.)

In [48]:
frame2

year   state  pop  debt
one    2000    Ohio  1.5   0.0
two    2001    Ohio  1.7   1.0
three  2002    Ohio  3.6   2.0
four   2001  Nevada  2.4   3.0
five   2002  Nevada  2.9   4.0
six    2003  Nevada  3.2   5.0

In [49]:
val = pd.Series([-1.2, -1.5, -1.7], index=['two', 'four', 'five'])

In [50]:
frame2['debt'] = val

In [51]:
frame2

year   state  pop  debt
one    2000    Ohio  1.5   NaN
two    2001    Ohio  1.7  -1.2
three  2002    Ohio  3.6   NaN
four   2001  Nevada  2.4  -1.5
five   2002  Nevada  2.9  -1.7
six    2003  Nevada  3.2   NaN

In [52]:
frame2['eastern'] = frame2.state == 'Ohio'

In [53]:
frame2.head()

year   state  pop  debt  eastern
one    2000    Ohio  1.5   NaN     True
two    2001    Ohio  1.7  -1.2     True
three  2002    Ohio  3.6   NaN     True
four   2001  Nevada  2.4  -1.5    False
five   2002  Nevada  2.9  -1.7    False

In [54]:
del frame2['eastern']

In [55]:
frame2.columns

Index(['year', 'state', 'pop', 'debt'], dtype='object')

In [71]:
pop = {'Nevada' : {2001:2.4, 2002 : 2.9},
        'Ohio' : {2000: 1.5, 2001: 1.7, 2002: 3.6}}

In [72]:
frame3 = pd.DataFrame(pop)

In [73]:
frame3

Nevada  Ohio
2001     2.4   1.7
2002     2.9   3.6
2000     NaN   1.5

In [74]:
frame3.T

2001  2002  2000
Nevada   2.4   2.9   NaN
Ohio     1.7   3.6   1.5

In [75]:
pd.DataFrame(pop, index=[2001, 2002, 2003])

Nevada  Ohio
2001     2.4   1.7
2002     2.9   3.6
2003     NaN   NaN

In [76]:
pdata = {'Ohio' : frame3['Ohio'][:-1],
         'Nevada' : frame3['Nevada'][:2]}

In [77]:
pd.DataFrame(pdata)

Ohio  Nevada
2001   1.7     2.4
2002   3.6     2.9

In [78]:
frame3.index.name = 'year'

In [79]:
frame3.columns.name = 'state'

In [80]:
frame3.values

array([[2.4, 1.7],
       [2.9, 3.6],
       [nan, 1.5]])

In [81]:
frame2.values

array([[2000, 'Ohio', 1.5, nan],
       [2001, 'Ohio', 1.7, -1.2],
       [2002, 'Ohio', 3.6, nan],
       [2001, 'Nevada', 2.4, -1.5],
       [2002, 'Nevada', 2.9, -1.7],
       [2003, 'Nevada', 3.2, nan]], dtype=object)

In [82]:
obj = pd.Series(range(3), index=['a', 'b', 'c'])

In [83]:
index = obj.index

In [84]:
index

Index(['a', 'b', 'c'], dtype='object')

In [85]:
index[1:]

Index(['b', 'c'], dtype='object')

In [86]:
index[1] = 'd'

TypeError: Index does not support mutable operations

In [87]:
labels = pd.Index(np.arange(3))

In [88]:
labels

Int64Index([0, 1, 2], dtype='int64')

In [89]:
obj2 = pd.Series([1.5, -2.5, 0], index=labels)

In [90]:
obj2

0    1.5
1   -2.5
2    0.0
dtype: float64

In [91]:
obj2.index is labels

True

In [92]:
frame3

state  Nevada  Ohio
year               
2001      2.4   1.7
2002      2.9   3.6
2000      NaN   1.5

In [93]:
'Ohio' in frame3.columns

True

In [94]:
2003 in frame3.index

False

In [95]:
dup_labels = pd.Index(['foo', 'foo', 'bar', 'bar'])

In [96]:
dup_labels

Index(['foo', 'foo', 'bar', 'bar'], dtype='object')

In [97]:
obj = pd.Series([4.5, 7.2, -5.3, 3.6], index=['d', 'b', 'a', 'c'])

In [98]:
obj2 = obj.reindex(['a', 'b', 'c', 'd', 'e'])

In [99]:
obj2

a   -5.3
b    7.2
c    3.6
d    4.5
e    NaN
dtype: float64

In [100]:
obj3 = pd.Series(['blue', 'purple', 'yellow'], index=[0, 2, 4])

In [101]:
obj3

0      blue
2    purple
4    yellow
dtype: object

In [102]:
obj3.reindex(range(6), method='ffill')

0      blue
1      blue
2    purple
3    purple
4    yellow
5    yellow
dtype: object

In [103]:
frame = pd.DataFrame(np.arange(9).reshape((3,3)),
                    index = ['a', 'c', 'd'],
                    columns = ['Ohio', 'Texas', 'California'])

In [104]:
frame

Ohio  Texas  California
a     0      1           2
c     3      4           5
d     6      7           8

In [105]:
frame2 = frame.reindex(['a', 'b', 'c', 'd'])

In [106]:
frame2

Ohio  Texas  California
a   0.0    1.0         2.0
b   NaN    NaN         NaN
c   3.0    4.0         5.0
d   6.0    7.0         8.0

In [107]:
states = ['Texas', 'Utah', 'California']

In [108]:
frame.reindex(columns=states)

Texas  Utah  California
a      1   NaN           2
c      4   NaN           5
d      7   NaN           8

In [110]:
frame

Ohio  Texas  California
a     0      1           2
c     3      4           5
d     6      7           8

In [111]:
frame.loc[['a', 'b', 'c', 'd'], states]

KeyError: "Passing list-likes to .loc or [] with any missing labels is no longer supported. The following labels were missing: Index(['b'], dtype='object'). See https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#deprecate-loc-reindex-listlike"

In [112]:
obj = pd.Series(np.arange(5.), index=['a', 'b', 'c', 'd', 'e'])

In [113]:
obj

a    0.0
b    1.0
c    2.0
d    3.0
e    4.0
dtype: float64

In [114]:
new_obj = obj.drop('c')

In [115]:
new_obj

a    0.0
b    1.0
d    3.0
e    4.0
dtype: float64

In [116]:
obj.drop(['d', 'c'])

a    0.0
b    1.0
e    4.0
dtype: float64

In [117]:
data = pd.DataFrame(np.arange(16).reshape(4, 4),
                   index=['Ohio', 'Colorado', 'Utah', 'New York'],
                   columns=['one', 'two', 'three', 'four'])

In [118]:
data

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [119]:
data.drop(['Colorado', 'Ohio'])

one  two  three  four
Utah        8    9     10    11
New York   12   13     14    15

In [120]:
data.drop('two', axis =1)

one  three  four
Ohio        0      2     3
Colorado    4      6     7
Utah        8     10    11
New York   12     14    15

In [121]:
obj.drop('c', inplace=True)

In [122]:
obj

a    0.0
b    1.0
d    3.0
e    4.0
dtype: float64

In [123]:
obj = pd.Series(np.arange(4.), index=['a', 'b', 'c', 'd'])

In [124]:
obj

a    0.0
b    1.0
c    2.0
d    3.0
dtype: float64

In [125]:
obj['b']

1.0

In [126]:
obj[1]

1.0

In [127]:
obj[2:4]

c    2.0
d    3.0
dtype: float64

In [128]:
obj[['b', 'a', 'd']]

b    1.0
a    0.0
d    3.0
dtype: float64

In [129]:
obj[[1, 3]]

b    1.0
d    3.0
dtype: float64

In [130]:
obj[obj < 2]

a    0.0
b    1.0
dtype: float64

In [131]:
obj['b':'c']

b    1.0
c    2.0
dtype: float64

In [132]:
obj['b':'c'] = 5

In [133]:
obj

a    0.0
b    5.0
c    5.0
d    3.0
dtype: float64

In [134]:
data = pd.DataFrame(np.arange(16).reshape((4,4)),
                   index=['Ohio', 'Colorado', 'Utah', 'New York'],
                   columns=['one', 'two', 'three', 'four'])

In [135]:
data

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [136]:
data['two']

Ohio         1
Colorado     5
Utah         9
New York    13
Name: two, dtype: int32

In [137]:
data[['three', 'one']]

three  one
Ohio          2    0
Colorado      6    4
Utah         10    8
New York     14   12

In [138]:
data[:2]

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7

In [139]:
data[data['three'] > 5]

one  two  three  four
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [140]:
data < 5

one    two  three   four
Ohio       True   True   True   True
Colorado   True  False  False  False
Utah      False  False  False  False
New York  False  False  False  False

In [141]:
data[data < 5] = 0

In [142]:
data

one  two  three  four
Ohio        0    0      0     0
Colorado    0    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [143]:
data.loc['Colorado', ['two', 'three']]

two      5
three    6
Name: Colorado, dtype: int32

In [144]:
data.iloc[2, [3, 0, 1]]

four    11
one      8
two      9
Name: Utah, dtype: int32

In [145]:
data.iloc[2]

one       8
two       9
three    10
four     11
Name: Utah, dtype: int32

In [146]:
data.iloc[[1, 2], [3, 0, 1]]

four  one  two
Colorado     7    0    5
Utah        11    8    9

In [147]:
data.loc[:'Utah', 'two']

Ohio        0
Colorado    5
Utah        9
Name: two, dtype: int32

In [148]:
data.iloc[:, :3][data.three > 5]

one  two  three
Colorado    0    5      6
Utah        8    9     10
New York   12   13     14

In [150]:
data.iloc[:, :3]

one  two  three
Ohio        0    0      0
Colorado    0    5      6
Utah        8    9     10
New York   12   13     14

In [151]:
ser = pd.Series(np.arange(3.))

In [152]:
ser

0    0.0
1    1.0
2    2.0
dtype: float64

In [154]:
ser2 = pd.Series(np.arange(3.), index=['a', 'b', 'c'])

In [155]:
ser2[-1]

2.0

In [156]:
ser[:1]

0    0.0
dtype: float64

In [157]:
ser.loc[:1]

0    0.0
1    1.0
dtype: float64

In [158]:
ser.iloc[:1]

0    0.0
dtype: float64

In [159]:
s1 = pd.Series([7.3, -2.5, 3.4, 1.5], index=['a', 'c', 'd', 'e'])

In [160]:
s2 = pd.Series([-2.1, 3.6, -1.5, 4, 3.1], index=['a', 'c', 'e', 'f', 'g'])

In [161]:
s1

a    7.3
c   -2.5
d    3.4
e    1.5
dtype: float64

In [162]:
s2

a   -2.1
c    3.6
e   -1.5
f    4.0
g    3.1
dtype: float64

In [163]:
s1 + s2

a    5.2
c    1.1
d    NaN
e    0.0
f    NaN
g    NaN
dtype: float64

In [164]:
df1 = pd.DataFrame(np.arange(9.).reshape((3, 3)), columns=list('bcd'), index=['Ohio', 'Texas', 'Colorado'])

In [165]:
df2 = pd.DataFrame(np.arange(12.).reshape((4,3)), columns=list('bde'), index=['Utah', 'Ohio', 'Texas', 'Oregon'])

In [166]:
df1

b    c    d
Ohio      0.0  1.0  2.0
Texas     3.0  4.0  5.0
Colorado  6.0  7.0  8.0

In [167]:
df2

b     d     e
Utah    0.0   1.0   2.0
Ohio    3.0   4.0   5.0
Texas   6.0   7.0   8.0
Oregon  9.0  10.0  11.0

In [168]:
df1 + df2

b   c     d   e
Colorado  NaN NaN   NaN NaN
Ohio      3.0 NaN   6.0 NaN
Oregon    NaN NaN   NaN NaN
Texas     9.0 NaN  12.0 NaN
Utah      NaN NaN   NaN NaN

In [169]:
df1 = pd.DataFrame({'A' : [1, 2]})
df2 = pd.DataFrame({'B' : [3, 4]})

In [170]:
df1

A
0  1
1  2

In [171]:
df2

B
0  3
1  4

In [172]:
df1 = pd.DataFrame(np.arange(12.).reshape((3, 4)), columns=list('abcd'))
df2 = pd.DataFrame(np.arange(20.).reshape((4, 5)), columns=list('abcde'))

In [173]:
df2.loc[1, 'b'] = np.nan

In [174]:
df1

a    b     c     d
0  0.0  1.0   2.0   3.0
1  4.0  5.0   6.0   7.0
2  8.0  9.0  10.0  11.0

In [175]:
df2

a     b     c     d     e
0   0.0   1.0   2.0   3.0   4.0
1   5.0   NaN   7.0   8.0   9.0
2  10.0  11.0  12.0  13.0  14.0
3  15.0  16.0  17.0  18.0  19.0

In [176]:
df1  + df2

a     b     c     d   e
0   0.0   2.0   4.0   6.0 NaN
1   9.0   NaN  13.0  15.0 NaN
2  18.0  20.0  22.0  24.0 NaN
3   NaN   NaN   NaN   NaN NaN

In [177]:
df1.add(df2, fill_value=0)

a     b     c     d     e
0   0.0   2.0   4.0   6.0   4.0
1   9.0   5.0  13.0  15.0   9.0
2  18.0  20.0  22.0  24.0  14.0
3  15.0  16.0  17.0  18.0  19.0

In [178]:
df1.rdiv(1)

a         b         c         d
0    inf  1.000000  0.500000  0.333333
1  0.250  0.200000  0.166667  0.142857
2  0.125  0.111111  0.100000  0.090909

In [179]:
1/ df1

a         b         c         d
0    inf  1.000000  0.500000  0.333333
1  0.250  0.200000  0.166667  0.142857
2  0.125  0.111111  0.100000  0.090909

In [180]:
df1.reindex(columns=df2.columns, fill_value=0)

a    b     c     d  e
0  0.0  1.0   2.0   3.0  0
1  4.0  5.0   6.0   7.0  0
2  8.0  9.0  10.0  11.0  0

In [181]:
arr = np.arange(12.).reshape((3, 4))

In [182]:
arr

array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.]])

In [183]:
arr[0]

array([0., 1., 2., 3.])

In [184]:
arr - arr[0]

array([[0., 0., 0., 0.],
       [4., 4., 4., 4.],
       [8., 8., 8., 8.]])

In [185]:
frame = pd.DataFrame(np.arange(12.).reshape((4, 3)), 
                      columns=list('bde'),
                      index=['Utah', 'Ohio', 'Texas', 'Oregon'])

In [186]:
series = frame.iloc[0]

In [187]:
frame

b     d     e
Utah    0.0   1.0   2.0
Ohio    3.0   4.0   5.0
Texas   6.0   7.0   8.0
Oregon  9.0  10.0  11.0

In [188]:
series

b    0.0
d    1.0
e    2.0
Name: Utah, dtype: float64

In [189]:
frame - series

b    d    e
Utah    0.0  0.0  0.0
Ohio    3.0  3.0  3.0
Texas   6.0  6.0  6.0
Oregon  9.0  9.0  9.0

In [191]:
series2 = pd.Series(range(3), index=['b', 'e', 'f'])

In [192]:
frame + series2

b   d     e   f
Utah    0.0 NaN   3.0 NaN
Ohio    3.0 NaN   6.0 NaN
Texas   6.0 NaN   9.0 NaN
Oregon  9.0 NaN  12.0 NaN

In [193]:
series3 = frame['d']

In [194]:
frame

b     d     e
Utah    0.0   1.0   2.0
Ohio    3.0   4.0   5.0
Texas   6.0   7.0   8.0
Oregon  9.0  10.0  11.0

In [195]:
series3

Utah       1.0
Ohio       4.0
Texas      7.0
Oregon    10.0
Name: d, dtype: float64

In [196]:
frame.sub(seires3, axis='index')

NameError: name 'seires3' is not defined

In [197]:
frame = pd.DataFrame(np.random.randn(4, 3), columns=list('bde'), 
                    index=['Utah', 'Ohio', 'Texas', 'Oregon'])

In [198]:
frame

b         d         e
Utah   -0.526557  3.040894  0.082492
Ohio   -0.569561 -0.274257  0.545350
Texas   0.068658  1.058743  0.803974
Oregon -0.145244 -0.986782  1.351432

In [199]:
np.abs(frame)

b         d         e
Utah    0.526557  3.040894  0.082492
Ohio    0.569561  0.274257  0.545350
Texas   0.068658  1.058743  0.803974
Oregon  0.145244  0.986782  1.351432

In [200]:
f = lambda x : x.max() - x.min()

In [201]:
frame.apply(f)

b    0.638220
d    4.027676
e    1.268940
dtype: float64

In [202]:
frame.apply(f, axis='columns')

Utah      3.567451
Ohio      1.114912
Texas     0.990085
Oregon    2.338214
dtype: float64

In [203]:
def f(x):
    return pd.Series([x.min(), x.max()], index=['min', 'max'])

In [204]:
frame.apply(f)

b         d         e
min -0.569561 -0.986782  0.082492
max  0.068658  3.040894  1.351432

In [205]:
format = lambda x : '%.2f' %x

In [206]:
frame.applymap(format)

b      d     e
Utah    -0.53   3.04  0.08
Ohio    -0.57  -0.27  0.55
Texas    0.07   1.06  0.80
Oregon  -0.15  -0.99  1.35

In [207]:
frame['e'].map(format)

Utah      0.08
Ohio      0.55
Texas     0.80
Oregon    1.35
Name: e, dtype: object

In [208]:
obj = pd.Series(range(4), index=['d', 'a', 'b', 'c'])

In [209]:
obj.sort_index()

a    1
b    2
c    3
d    0
dtype: int64

In [210]:
frame = pd.DataFrame(np.arange(8).reshape((2, 4)), 
                     index=['three', 'one'],
                     columns=['d', 'a', 'b', 'c'])

In [211]:
frame.sort_index()

d  a  b  c
one    4  5  6  7
three  0  1  2  3

In [213]:
frame.sort_index(axis=1)

a  b  c  d
three  1  2  3  0
one    5  6  7  4

In [214]:
frame.sort_index(axis=1, ascending=False)

d  c  b  a
three  0  3  2  1
one    4  7  6  5

In [216]:
obj = pd.Series([4, 7, -3, 2])

In [217]:
obj.sort_values()

2   -3
3    2
0    4
1    7
dtype: int64

In [218]:
obj = pd.Series([4, np.nan, 7, np.nan, -3, 2])

In [219]:
obj.sort_values()

4   -3.0
5    2.0
0    4.0
2    7.0
1    NaN
3    NaN
dtype: float64

In [239]:
frame = pd.DataFrame({'b' : [4, 7, -3, 2], 'a' : [0, 1, 0, 1]})

In [221]:
frame

b  a
0  4  0
1  7  1
2 -3  0
3  2  1

In [222]:
frame.sort_values(by='b')

b  a
2 -3  0
3  2  1
0  4  0
1  7  1

In [240]:
frame.sort_values(by=['a', 'b'])

b  a
2 -3  0
0  4  0
3  2  1
1  7  1

In [241]:
frame.sort_values(by=['a', 'b']).columns = ['a', 'b']

In [242]:
frame

b  a
0  4  0
1  7  1
2 -3  0
3  2  1

In [243]:
frame = frame[['a', 'b']]

In [244]:
frame

a  b
0  0  4
1  1  7
2  0 -3
3  1  2

In [245]:
obj = pd.Series([7, -5, 7, 4, 2, 0, 4])

In [246]:
obj.rank()

0    6.5
1    1.0
2    6.5
3    4.5
4    3.0
5    2.0
6    4.5
dtype: float64

In [247]:
obj.rank(method='first')

0    6.0
1    1.0
2    7.0
3    4.0
4    3.0
5    2.0
6    5.0
dtype: float64

In [248]:
obj.rank(ascending=False, method='max')

0    2.0
1    7.0
2    2.0
3    4.0
4    5.0
5    6.0
6    4.0
dtype: float64

In [249]:
frame = pd.DataFrame({'b' : [4.3, 7, -3, 2], 'a' : [0, 1, 0, 1], 'c' : [-2, 5, 7, -2.5]})

In [250]:
frame

b  a    c
0  4.3  0 -2.0
1  7.0  1  5.0
2 -3.0  0  7.0
3  2.0  1 -2.5

In [251]:
frame = frame[['a', 'b', 'c']]

In [252]:
frame

a    b    c
0  0  4.3 -2.0
1  1  7.0  5.0
2  0 -3.0  7.0
3  1  2.0 -2.5

In [253]:
obj = pd.Series(range(5), index=['a', 'a', 'b', 'b', 'c'])

In [254]:
obj

a    0
a    1
b    2
b    3
c    4
dtype: int64

In [255]:
obj.index.is_unique

False

In [256]:
obj['a']

a    0
a    1
dtype: int64

In [257]:
obj['c']

4

In [258]:
df = pd.DataFrame(np.random.randn(4, 3), index=['a', 'a', 'b', 'b'])

In [259]:
df

0         1         2
a -0.145136 -0.605218 -0.996914
a -1.394895  0.240551 -1.087147
b  1.108541  0.024155  0.121933
b  2.726059 -2.414741  0.492426

In [260]:
df.loc['b']

0         1         2
b  1.108541  0.024155  0.121933
b  2.726059 -2.414741  0.492426

In [262]:
df = pd.DataFrame([[1.4, np.nan], [7.1, -4.5], [np.nan, np.nan], [0.75, -1.3]], index=['a', 'b', 'c', 'd'], columns=['one','two'])

In [263]:
df

one  two
a  1.40  NaN
b  7.10 -4.5
c   NaN  NaN
d  0.75 -1.3

In [264]:
df.sum()

one    9.25
two   -5.80
dtype: float64

In [265]:
df.sum(axis='columns')

a    1.40
b    2.60
c    0.00
d   -0.55
dtype: float64

In [266]:
df.mean(axis='columns', skipna=False)

a      NaN
b    1.300
c      NaN
d   -0.275
dtype: float64

In [267]:
df.idxmax()

one    b
two    d
dtype: object

In [269]:
df.cumsum()

one  two
a  1.40  NaN
b  8.50 -4.5
c   NaN  NaN
d  9.25 -5.8

In [270]:
df.describe()

one       two
count  3.000000  2.000000
mean   3.083333 -2.900000
std    3.493685  2.262742
min    0.750000 -4.500000
25%    1.075000 -3.700000
50%    1.400000 -2.900000
75%    4.250000 -2.100000
max    7.100000 -1.300000

In [271]:
obj = pd.Series(['a', 'a', 'b', 'c' ] * 4)

In [272]:
obj.describe()

count     16
unique     3
top        a
freq       8
dtype: object

In [274]:
pip install pandas-datareader

Note: you may need to restart the kernel to use updated packages.


You should consider upgrading via the 'C:\ProgramData\Anaconda3\python.exe -m pip install --upgrade pip' command.


In [275]:
import pandas_datareader.data as web

In [276]:
all_data = {ticker : web.get_data_yahoo(ticker) for ticker in ['AAPL', 'IBM', 'MSFT', 'GOOG']}

In [277]:
price = pd.DataFrame({ticker:data['Adj Close'] for ticker, data in all_data.items()})

In [278]:
all_data

{'AAPL':                   High         Low        Open       Close       Volume  \
 Date                                                                      
 2015-09-22   28.545000   28.129999   28.344999   28.350000  201384800.0   
 2015-09-23   28.680000   28.325001   28.407499   28.580000  143026800.0   
 2015-09-24   28.875000   28.092501   28.312500   28.750000  200878000.0   
 2015-09-25   29.172501   28.504999   29.110001   28.677500  224607600.0   
 2015-09-28   28.642500   28.110001   28.462500   28.110001  208436000.0   
 ...                ...         ...         ...         ...          ...   
 2020-09-14  115.930000  112.800003  114.720001  115.360001  140150100.0   
 2020-09-15  118.830002  113.610001  118.330002  115.540001  184642000.0   
 2020-09-16  116.000000  112.040001  115.230003  112.129997  154679000.0   
 2020-09-17  112.199997  108.709999  109.720001  110.339996  178011000.0   
 2020-09-18  110.879997  106.089996  110.400002  106.839996  286693600.0   
 
  

In [279]:
price

AAPL         IBM        MSFT         GOOG
Date                                                       
2015-09-22   26.198639  115.659622   39.896111   622.690002
2015-09-23   26.411180  115.042992   39.868851   622.359985
2015-09-24   26.568277  115.643631   39.905201   625.799988
2015-09-25   26.501280  116.452400   39.932461   611.969971
2015-09-28   25.976849  114.130112   39.341743   594.890015
...                ...         ...         ...          ...
2020-09-14  115.360001  122.089996  205.410004  1519.280029
2020-09-15  115.540001  122.440002  208.779999  1541.439941
2020-09-16  112.129997  124.220001  205.050003  1520.900024
2020-09-17  110.339996  124.919998  202.910004  1495.530029
2020-09-18  106.839996  122.760002  200.389999  1459.989990

[1258 rows x 4 columns]

In [280]:
volume = pd.DataFrame({ticker : data['Volume'] for ticker, data in all_data.items()})

In [281]:
volume

AAPL        IBM        MSFT     GOOG
Date                                                   
2015-09-22  201384800.0  3564100.0  28085900.0  2562900
2015-09-23  143026800.0  2674200.0  17145200.0  1470900
2015-09-24  200878000.0  3280300.0  27905600.0  2240100
2015-09-25  224607600.0  3474400.0  29384600.0  2174000
2015-09-28  208436000.0  4317300.0  27613800.0  3127700
...                 ...        ...         ...      ...
2020-09-14  140150100.0  3641500.0  30375800.0  1696600
2020-09-15  184642000.0  2915200.0  21823900.0  1331100
2020-09-16  154679000.0  3788400.0  26328100.0  1311700
2020-09-17  178011000.0  3171300.0  34011300.0  1879800
2020-09-18  286693600.0  5389800.0  55199500.0  3101800

[1258 rows x 4 columns]

In [282]:
returns = price.pct_change()

In [283]:
returns.tail()

AAPL       IBM      MSFT      GOOG
Date                                              
2020-09-14  0.030000  0.005187  0.006764 -0.000947
2020-09-15  0.001560  0.002867  0.016406  0.014586
2020-09-16 -0.029514  0.014538 -0.017866 -0.013325
2020-09-17 -0.015964  0.005635 -0.010436 -0.016681
2020-09-18 -0.031720 -0.017291 -0.012419 -0.023764

In [285]:
returns.MSFT.corr(returns.IBM)

0.5761917543259154

In [286]:
corr(returns['MSFT'], returns['IBM'])

NameError: name 'corr' is not defined

In [288]:
returns['MSFT'].corr(returns['IBM'])

0.5761917543259154

In [289]:
returns.corr()

AAPL       IBM      MSFT      GOOG
AAPL  1.000000  0.498388  0.703872  0.655596
IBM   0.498388  1.000000  0.576192  0.534534
MSFT  0.703872  0.576192  1.000000  0.783305
GOOG  0.655596  0.534534  0.783305  1.000000

In [291]:
returns.cov()

AAPL       IBM      MSFT      GOOG
AAPL  0.000348  0.000149  0.000229  0.000202
IBM   0.000149  0.000257  0.000161  0.000141
MSFT  0.000229  0.000161  0.000306  0.000226
GOOG  0.000202  0.000141  0.000226  0.000273

In [292]:
returns.corrwith(returns.IBM)

AAPL    0.498388
IBM     1.000000
MSFT    0.576192
GOOG    0.534534
dtype: float64

In [293]:
returns.corrwith(volume)

AAPL   -0.071676
IBM    -0.098103
MSFT   -0.054559
GOOG   -0.150853
dtype: float64

In [294]:
obj = pd.Series(['c', 'a', 'd', 'a', 'a', 'b', 'b', 'c', 'c'])

In [295]:
uniques = obj.unique()

In [297]:
uniques

array(['c', 'a', 'd', 'b'], dtype=object)

In [298]:
obj.value_counts()

a    3
c    3
b    2
d    1
dtype: int64

In [299]:
pd.value_counts(obj.values, sort=False)

c    3
d    1
a    3
b    2
dtype: int64

In [300]:
obj.value_counts(sort=False)

c    3
d    1
a    3
b    2
dtype: int64

In [301]:
obj

0    c
1    a
2    d
3    a
4    a
5    b
6    b
7    c
8    c
dtype: object

In [303]:
mask= obj.isin(['b', 'c'])

In [305]:
mask

0     True
1    False
2    False
3    False
4    False
5     True
6     True
7     True
8     True
dtype: bool

In [306]:
obj[mask]

0    c
5    b
6    b
7    c
8    c
dtype: object

In [307]:
to_match = pd.Series(['c', 'a', 'b', 'b', 'c', 'a'])

In [308]:
unique_vals = pd.Series(['c', 'b', 'a'])

In [309]:
pd.Index(unique_vals).get_indexer(to_match)

array([0, 2, 1, 1, 0, 2], dtype=int64)

In [310]:
data = pd.DataFrame({'Qu1' : [1, 3, 4, 3, 4],
                    'Qu2' : [2, 3, 1, 2, 3],
                    'Qu3' : [1, 5, 2, 4, 4]})

In [311]:
data

Qu1  Qu2  Qu3
0    1    2    1
1    3    3    5
2    4    1    2
3    3    2    4
4    4    3    4

In [313]:
result = data.apply(pd.value_counts).fillna(0)

In [314]:
result

Qu1  Qu2  Qu3
1  1.0  1.0  1.0
2  0.0  2.0  1.0
3  2.0  2.0  0.0
4  2.0  0.0  2.0
5  0.0  0.0  1.0