In [1]:
import numpy as np
a = np.array([[1., 2.], [3., 4.]])
np.linalg.inv(a) # 역행렬

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

In [3]:
np.linalg.det(a) # 행렬식

-2.0000000000000004

### 고유값, 고유벡터, 주성분분석

In [3]:
from sklearn.decomposition import PCA
M = np.array([[-1, -1, -1], [-2, -1, 2], [-3, -2, 0], [1, 1, 2], [2, 1, 1], [3, 2, 4], [2, 0, 3], [3, 5, 1], [4, 2, 3], [3, 3, 2]])
# 주성분 2개로 지정
pca = PCA(n_components=2) 
pca.fit(M)
PC = pca.transform(M)
# w는 고유값, V는 고유벡터
w, V = np.linalg.eig(pca.get_covariance())
# 원래 데이터를 나타내는 주성분 3개
V.T.dot(M.T).T

array([[-1.63789386,  0.38309423, -0.41296792],
       [-1.50265209, -1.67967793,  1.98008049],
       [-3.43143719, -0.83088857,  0.73134327],
       [ 1.9287851 , -0.84878936,  1.24873722],
       [ 2.3753258 ,  0.28259255,  0.52722744],
       [ 4.59500215, -1.03189193,  2.61173397],
       [ 2.3475376 , -0.06571181,  2.73582697],
       [ 5.55104049, -1.38406422, -1.5067567 ],
       [ 5.04154285,  0.09948998,  1.89022418],
       [ 4.62279035, -0.68358757,  0.40313444]])

In [8]:
import numpy as np
from scipy import linalg, sparse

A = np.matrix(np.random.random((2, 2)))
# 2 by 2 numpy array 
b = np.random.random((2, 2))
# 2차원 배열을 행렬로 변환
B = np.asmatrix(b)
# 임의의 10 by 5 행렬
C = np.mat(np.random.random((10, 5)))
# 2차원 자료를 나타낸 리스트를 행렬로 표현
D = np.mat([[3, 4], [5, 6]]) 

In [9]:
print(A)

[[0.77504325 0.34849986]
 [0.48750012 0.78527493]]


In [10]:
print(B)

[[0.79169908 0.23892084]
 [0.9506816  0.98589278]]


In [11]:
print(C)

[[0.46260862 0.08736625 0.88852474 0.04863861 0.4743236 ]
 [0.71825151 0.49717577 0.22615483 0.57771856 0.769216  ]
 [0.51768948 0.2485036  0.32409291 0.63985036 0.91814631]
 [0.27960517 0.28796555 0.17587318 0.66015508 0.24985594]
 [0.92309264 0.32908906 0.59602843 0.55539959 0.13273521]
 [0.77616042 0.58650215 0.45041512 0.03042282 0.35159808]
 [0.49938905 0.315228   0.96773728 0.07532623 0.82601999]
 [0.14574673 0.53803676 0.6865556  0.76563601 0.18205684]
 [0.60753287 0.90091493 0.97936252 0.03194373 0.09939223]
 [0.44833099 0.83810643 0.21177602 0.30947921 0.64002835]]


In [12]:
print(D)

[[3 4]
 [5 6]]


In [13]:
A.I

matrix([[ 1.78988892, -0.79434096],
        [-1.11116634,  1.76656768]])

In [14]:
linalg.det(A)

0.4387283056642382

In [15]:
A.T

matrix([[0.77504325, 0.48750012],
        [0.34849986, 0.78527493]])

In [16]:
np.add(A, D)

matrix([[3.77504325, 4.34849986],
        [5.48750012, 6.78527493]])

In [17]:
np.subtract(A, D)

matrix([[-2.22495675, -3.65150014],
        [-4.51249988, -5.21472507]])

In [18]:
np.divide(A, D)

matrix([[0.25834775, 0.08712497],
        [0.09750002, 0.13087916]])

In [19]:
# D와 B의 행렬곱을 @로 계산
print(D@B)

[[6.17782364 4.66033363]
 [9.662585   7.10996086]]


In [20]:
# D와 B의 행렬곱 using dot
print(np.dot(D, B))

[[6.17782364 4.66033363]
 [9.662585   7.10996086]]


In [21]:
# 행렬곱이 아닌 대응되는 원소끼리의 단순 곱셈 수행
print(np.multiply(D, B))

[[2.37509723 0.95568335]
 [4.75340801 5.91535667]]


In [22]:
# 2 by 2 항등행렬
G = np.mat(np.identity(2))

In [23]:
G

matrix([[1., 0.],
        [0., 1.]])

In [24]:
# 고유값 확인
linalg.eigvals(A)

array([0.36794568+0.j, 1.1923725 +0.j])

In [25]:
# A의 고유 벡터
la, v = linalg.eig(A)

In [26]:
# 고유값을 l1, l2로 받기
l1, l2 = la

In [27]:
# 첫 번째 고유 벡터
v[:, 0]

array([-0.65031695,  0.75966299])

In [28]:
# 두 번째 고유 벡터
v[:, 1]

array([-0.64097154, -0.76756465])

In [29]:
C[C > 0.5] = 0

In [30]:
# C를 희소행렬로 변환
H = sparse.csr_matrix(C)

In [31]:
# H를 일반적인 행렬(dense matrix) 형태로 변환
H.todense()

matrix([[0.46260862, 0.08736625, 0.        , 0.04863861, 0.4743236 ],
        [0.        , 0.49717577, 0.22615483, 0.        , 0.        ],
        [0.        , 0.2485036 , 0.32409291, 0.        , 0.        ],
        [0.27960517, 0.28796555, 0.17587318, 0.        , 0.24985594],
        [0.        , 0.32908906, 0.        , 0.        , 0.13273521],
        [0.        , 0.        , 0.45041512, 0.03042282, 0.35159808],
        [0.49938905, 0.315228  , 0.        , 0.07532623, 0.        ],
        [0.14574673, 0.        , 0.        , 0.        , 0.18205684],
        [0.        , 0.        , 0.        , 0.03194373, 0.09939223],
        [0.44833099, 0.        , 0.21177602, 0.30947921, 0.        ]])

In [32]:
# 희소행렬 여부 확인
sparse.isspmatrix_csr(H)

True